modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "the_beyond.mixins.json"
[[mixins]]
config = "the_beyond.client.mixins.json"
[[mixins]]
config = "the_beyond_dimensional_tears.mixins.json"
[[mixins]]
config = "the_beyond_betterend_compat.mixins.json"
[[mixins]]
config = "the_beyond_stellarity_compat.mixins.json"
[[mixins]]
config = "the_beyond_compass_compat.mixins.json"
[[mixins]]
config = "the_beyond_quark_compat.mixins.json"

[[mods]]
enumExtensions="META-INF/enumextensions.json"
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
