package com.thebeyond.client.model.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class EnatiousTotemAnimations {
        public static final AnimationDefinition SPAWN = AnimationDefinition.Builder.withLength(1.44F)
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.degreeVec(0.0F, 34.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.degreeVec(0.0F, 34.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 75.47F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.degreeVec(0.0F, 75.47F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 110.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.degreeVec(0.0F, 110.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, 165.49F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.degreeVec(0.0F, 165.49F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 208.92F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.degreeVec(0.0F, 208.92F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, 287.39F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.039F, KeyframeAnimations.degreeVec(0.0F, 287.39F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.04F, KeyframeAnimations.degreeVec(0.0F, 310.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.079F, KeyframeAnimations.degreeVec(0.0F, 310.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.degreeVec(0.0F, 362.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.239F, KeyframeAnimations.degreeVec(0.0F, 362.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.359F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.36F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.439F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.44F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -48.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.posVec(0.0F, -48.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.posVec(0.0F, -48.87F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.posVec(0.0F, -48.87F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, -50.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.posVec(0.0F, -50.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, -52.29F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.posVec(0.0F, -52.29F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, -48.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.posVec(0.0F, -48.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, -40.82F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.posVec(0.0F, -40.82F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -31.74F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.posVec(0.0F, -31.74F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, -22.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.posVec(0.0F, -22.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, -12.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.posVec(0.0F, -12.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, -3.24F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.posVec(0.0F, -3.24F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.17F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.posVec(0.0F, 0.17F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.posVec(0.0F, 0.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.439F, KeyframeAnimations.posVec(0.0F, 0.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.44F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0007F, 1.0F, 1.0007F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.scaleVec(1.0007F, 1.0F, 1.0007F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.scaleVec(1.0005F, 1.0F, 1.0005F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.439F, KeyframeAnimations.scaleVec(1.0005F, 1.0F, 1.0005F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.44F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.degreeVec(0.0F, 48.33F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.degreeVec(0.0F, 48.33F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 109.18F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.degreeVec(0.0F, 109.18F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 171.81F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.degreeVec(0.0F, 171.81F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, 241.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.degreeVec(0.0F, 241.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 305.39F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.degreeVec(0.0F, 305.39F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.degreeVec(0.0F, 330.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.degreeVec(0.0F, 330.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.999F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 362.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.079F, KeyframeAnimations.degreeVec(0.0F, 362.91F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.239F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -32.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.posVec(0.0F, -32.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.posVec(0.0F, -32.58F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.posVec(0.0F, -32.58F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, -33.35F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.posVec(0.0F, -33.35F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, -34.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.posVec(0.0F, -34.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, -32.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.posVec(0.0F, -32.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, -27.22F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.posVec(0.0F, -27.22F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -21.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.posVec(0.0F, -21.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, -14.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.posVec(0.0F, -14.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, -8.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.posVec(0.0F, -8.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, -2.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.posVec(0.0F, -2.16F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.posVec(0.0F, 0.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.posVec(0.0F, 0.04F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.239F, KeyframeAnimations.posVec(0.0F, 0.04F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0009F, 1.0F, 1.0009F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.159F, KeyframeAnimations.scaleVec(1.0009F, 1.0F, 1.0009F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.16F, KeyframeAnimations.scaleVec(1.0002F, 1.0F, 1.0002F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.239F, KeyframeAnimations.scaleVec(1.0002F, 1.0F, 1.0002F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.degreeVec(0.0F, -6.51F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.degreeVec(0.0F, -15.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.degreeVec(0.0F, -32.21F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.degreeVec(0.0F, 60.83F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.degreeVec(0.0F, 60.83F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 137.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.degreeVec(0.0F, 137.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 219.72F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.degreeVec(0.0F, 219.72F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, 299.53F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.degreeVec(0.0F, 299.53F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.079F, KeyframeAnimations.degreeVec(0.0F, 356.6F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -17.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.posVec(0.0F, -17.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.posVec(0.0F, -17.31F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.posVec(0.0F, -17.31F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, -17.72F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.posVec(0.0F, -17.72F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, -18.52F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.posVec(0.0F, -18.52F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, -17.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.posVec(0.0F, -17.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, -14.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.posVec(0.0F, -14.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -11.24F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.posVec(0.0F, -11.24F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, -7.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.posVec(0.0F, -7.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, -4.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.posVec(0.0F, -4.32F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, -1.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.posVec(0.0F, -1.15F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.079F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.159F, KeyframeAnimations.scaleVec(0.7964F, 1.0F, 0.7964F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.16F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.319F, KeyframeAnimations.scaleVec(0.7916F, 1.0F, 0.7916F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.439F, KeyframeAnimations.scaleVec(0.7821F, 1.0F, 0.7821F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.519F, KeyframeAnimations.scaleVec(0.8F, 1.0F, 0.8F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.599F, KeyframeAnimations.scaleVec(0.8299F, 1.0F, 0.8299F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.679F, KeyframeAnimations.scaleVec(0.8677F, 1.0F, 0.8677F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.68F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.759F, KeyframeAnimations.scaleVec(0.9076F, 1.0F, 0.9076F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.839F, KeyframeAnimations.scaleVec(0.9492F, 1.0F, 0.9492F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.879F, KeyframeAnimations.scaleVec(0.9865F, 1.0F, 0.9865F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.88F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.959F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .build();

        public static final AnimationDefinition SHOOT = AnimationDefinition.Builder.withLength(1.24F)
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 0.0F, -2.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 0.0F, 7.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 6.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.36F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.4F, KeyframeAnimations.scaleVec(1.0F, 1.2F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48F, KeyframeAnimations.scaleVec(1.0F, 1.1333F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8F, KeyframeAnimations.posVec(0.0F, 0.0F, -2.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, 0.0F, 7.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.92F, KeyframeAnimations.posVec(0.0F, 0.0F, 6.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12F, KeyframeAnimations.posVec(0.0F, 0.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.72F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.76F, KeyframeAnimations.scaleVec(1.0F, 1.2F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.0F, 1.1667F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0F, 1.0333F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.64F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.92F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12F, KeyframeAnimations.posVec(0.0F, 0.0F, 2.25F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.0F, KeyframeAnimations.scaleVec(1.0F, 1.2F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.12F, KeyframeAnimations.scaleVec(1.0F, 1.1F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1.24F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .build();

        public static final AnimationDefinition RECHARGE = AnimationDefinition.Builder.withLength(4.5F)
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(2.15F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.6F, KeyframeAnimations.degreeVec(0.0F, 380.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.7F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.2F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone3", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(2.15F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.2F, KeyframeAnimations.scaleVec(1.2F, 1.0F, 1.2F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.35F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(2.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.55F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.65F, KeyframeAnimations.degreeVec(0.0F, 380.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.75F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(4.05F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.25F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.3F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(2.1F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.15F, KeyframeAnimations.scaleVec(1.2F, 1.0F, 1.2F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.3F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(2.35F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.6F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.7F, KeyframeAnimations.degreeVec(0.0F, 380.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.8F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(4.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.3F, KeyframeAnimations.posVec(0.0F, 3.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(4.35F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("bone", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.05F, KeyframeAnimations.scaleVec(1.2F, 1.0F, 1.2F), AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2.2F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .build();
}
